export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_REQUEST_SUCCESS = "SIGNUP_REQUEST_SUCCESS";
export const SIGNUP_REQUEST_FAIL = "SIGNUP_REQUEST_FAIL";

export const ADD_HOTELS = "ADD_HOTELS";
export const ADD_HOTELS_SUCCESS = "ADD_HOTELS-SUCCESS";
export const ADD_HOTELS_FAIL = "ADD_HOTELS_FAIL";
export const PREVIOUS_HOTEL_DATA = "PREVIOUS_HOTEL_DATA";
export const ADD_HOTELS_DATA = "ADD_HOTELS_DATA";
export const SAVE_HOTEL_DETAILS = "SAVE_HOTEL_DETAILS";
export const UPDATE_HOTEL_DETAILS = "UPDATE_HOTEL_DETAILS";
export const DELETE_HOTEL="DELETE_HOTEL";

export const REQUEST_STARTED = "REQUEST_STARTED";
export const REQUEST_COMPLETED = "REQUEST_COMPLETED";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";
export const LOGIN_REQUEST_FAIL = "LOGIN_REQUEST_FAIL";

export const BUS_REQUEST_SUCCESS = "BUS_REQUEST_SUCCESS";
export const BUS_REQUEST_FAIL = "BUS_REQUEST_FAIL";
export const BUS_BY_ID_REQUEST_SUCCESS = "BUS_BY_ID_REQUEST_SUCCESS";

export const TRAIN_REQUEST_SUCCESS = "TRAIN_REQUEST_SUCCESS";
export const TRAIN_REQUEST_FAIL = "TRAIN_REQUEST_FAIL";
export const TRAIN_BY_ID_REQUEST_SUCCESS = "TRAIN_BY_ID_REQUEST_SUCCESS";
